import { OrderForm } from "@/components/order-form";

export default function Home() {
  return (
    <div className="flex flex-col flex-1">
      {/* Header */}
      <header className="border-b border-border/50 px-6 py-4">
        <div className="max-w-5xl mx-auto flex items-center justify-between">
          <span className="text-xl font-bold tracking-tight">
            Pay<span className="gradient-text">Brief</span>
          </span>
          <span className="text-sm text-muted-foreground">
            Powered by Locus
          </span>
        </div>
      </header>

      {/* Hero */}
      <main className="flex-1">
        <section className="max-w-5xl mx-auto px-6 pt-20 pb-16">
          <div className="text-center mb-16">
            <div className="inline-block mb-4 px-3 py-1 rounded-full bg-primary/10 border border-primary/20 text-sm text-primary-light">
              AI-Powered Market Intelligence
            </div>
            <h1 className="text-5xl sm:text-6xl font-bold tracking-tight mb-6">
              Market briefs in
              <br />
              <span className="gradient-text">minutes, not days</span>
            </h1>
            <p className="text-lg text-muted-foreground max-w-2xl mx-auto mb-8">
              Enter a company name, pay 5 USDC, and get a comprehensive
              competitor analysis, pricing breakdown, and market overview
              generated by AI research agents.
            </p>
          </div>

          {/* How it works */}
          <div className="grid grid-cols-1 sm:grid-cols-3 gap-6 mb-20">
            {[
              {
                step: "1",
                title: "Enter a company",
                desc: "Tell us which company or product you want researched",
              },
              {
                step: "2",
                title: "Pay 5 USDC",
                desc: "Quick checkout via Locus — USDC on Base chain",
              },
              {
                step: "3",
                title: "Get your brief",
                desc: "AI agents research, scrape, and synthesize your report",
              },
            ].map((item) => (
              <div
                key={item.step}
                className="rounded-xl bg-card border border-border p-6"
              >
                <div className="w-8 h-8 rounded-full bg-primary/20 text-primary-light flex items-center justify-center text-sm font-bold mb-3">
                  {item.step}
                </div>
                <h3 className="font-semibold mb-1">{item.title}</h3>
                <p className="text-sm text-muted-foreground">{item.desc}</p>
              </div>
            ))}
          </div>

          {/* Order Form */}
          <div className="max-w-lg mx-auto">
            <div className="rounded-2xl bg-card border border-border p-8">
              <h2 className="text-2xl font-bold mb-2">Get your brief</h2>
              <p className="text-muted-foreground mb-6">
                Fill in the details below to start your market research.
              </p>
              <OrderForm />
            </div>
          </div>
        </section>
      </main>

      {/* Footer */}
      <footer className="border-t border-border/50 px-6 py-6 mt-auto">
        <div className="max-w-5xl mx-auto flex items-center justify-between text-sm text-muted-foreground">
          <span>PayBrief — Locus Paygentic Hackathon</span>
          <span>Built with Locus Checkout + Wrapped APIs</span>
        </div>
      </footer>
    </div>
  );
}
